apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ template "nfs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nfs.fullname" . }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ template "nfs.fullname" . }}
    path: "/"
