apiVersion: v1
kind: Service
metadata:
  name: {{ template "nfs.fullname" . }}
  labels:
    app: {{ template "nfs.name" . }}
    chart: {{ template "nfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 2049
      targetPort: nfs
      protocol: TCP
      name: nfs
    - port: 20048
      targetPort: mountd
      protocol: TCP
      name: mountd
    - port: 111
      targetPort: rpcbind
      protocol: TCP
      name: rpcbind
  selector:
    app: {{ template "nfs.name" . }}
    release: {{ .Release.Name }}
